---
# Source: myapp-ocp/templates/configmap-nginx-main.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-ocp-nginx-main-conf
  labels:
    helm.sh/chart: myapp-ocp-0.1.3
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
data:
  nginx.conf: |
    worker_processes  auto;
    error_log  /dev/stderr warn;
    pid        /tmp/nginx.pid;

    events { worker_connections  1024; }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      access_log /dev/stdout;

      sendfile        on;
      keepalive_timeout  65;

      client_body_temp_path /tmp/client_body_temp;
      proxy_temp_path       /tmp/proxy_temp;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;

      include /etc/nginx/conf.d/*.conf;
    }
---
# Source: myapp-ocp/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-ocp-nginx-conf
  labels:
    helm.sh/chart: myapp-ocp-0.1.3
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
data:
  default.conf: |
    server {
      listen 8080;
      listen [::]:8080;
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
---
# Source: myapp-ocp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-ocp
  labels:
    helm.sh/chart: myapp-ocp-0.1.3
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
---
# Source: myapp-ocp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-ocp
  labels:
    helm.sh/chart: myapp-ocp-0.1.3
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp-ocp
      app.kubernetes.io/instance: myapp-ocp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp-ocp
        app.kubernetes.io/instance: myapp-ocp
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: myapp-ocp
          image: "nginx:1.21.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: nginx-tmp
              mountPath: /tmp
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-main-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: myapp-ocp-nginx-conf
        - name: nginx-main-conf
          configMap:
            name: myapp-ocp-nginx-main-conf
---
# Source: myapp-ocp/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: myapp-ocp
  labels:
    helm.sh/chart: myapp-ocp-0.1.3
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  host: "myapp.apps.crc.testing"
  to:
    kind: Service
    name: myapp-ocp
  port:
    targetPort: http
---
# Source: myapp-ocp/templates/tests/test-service.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "myapp-ocp-test"
  labels:
    helm.sh/chart: myapp-ocp-0.1.3
    app.kubernetes.io/name: myapp-ocp
    app.kubernetes.io/instance: myapp-ocp
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
spec:
  restartPolicy: Never
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: wget
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
        - |
          set -e
          echo "Testing service HTTP..."
          wget -qO- "http://myapp-ocp:80/" | head -n 5
          echo "OK"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: tmp
      emptyDir: {}
